# ==============================================================
# DATASOURCE (Conexão MySQL)
# ==============================================================
# A flag 'createDatabaseIfNotExist=true' cria o schema automaticamente se não existir
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# JPA / HIBERNATE
# ==============================================================
# 'update' altera o schema da base de dados com base nas Entities (sem apagar dados existentes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logs de SQL para facilitar o debug durante o desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# SERVIDOR
# ==============================================================
server.port=8080